config/routes.rb
Run::Application.routes.draw do

  devise_for :general_users , :controllers => { :registrations => "general_users/registrations" , :sessions => "general_users/sessions" }
  resources :comments

  resources :records

  resources :team_albums

  resources :diary_images

  resources :teams

  resources :diaries

  resources :users
  resources :my_teams

  get "/auth/:provider/callback" => "sessions#callback"
  get '/index' => 'my_pages#index'
  get "teams/pass_check"
  post "/login" => "sessions#check"
  get '/sign_up' => "devise/registrations#new"
  post "teams/pass_check"
  post "teams/show"
  post 'my_pages/like'
  post 'my_pages/confirm'
  post 'my_teams/confirm'
  post 'my_teams/like'
  post 'diaries/data_save'
  post 'comments/save_comment' 
  get '/my_teams' => 'my_teams#index'
  get 'my_pages/like'
  get 'lps/index' => 'lps#index'
  get 'members/index'

  root :to => "my_pages#index"

  resources :tech_logs
  resources :members

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/diary.rb
class Diary < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :users
	has_reputation :likes, source: :user, aggregated_by: :sum

	validates :menu, presence: true
	validates :date, presence: true
	validates :subtitle, presence: true
	validates :other, presence: true


end

app/models/diary_image.rb
class DiaryImage < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/diary_images.rb
class DiaryImages < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/general_user.rb
class GeneralUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
  mount_uploader :image, ImageUploader

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_secure_password 
	validates :name, presence: true
	validates :destination , presence: true
	validates :image, presence: true
end

app/models/team_album.rb
class TeamAlbum < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :image, presence: true
	validates :title, presence: true
end

app/models/tech_log.rb
class TechLog < ActiveRecord::Base
	mount_uploader :video, VideoUploader

	validates :title, presence: true
	validates :video, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :name, presence: true
	validates :destination, presence: true

	@@auth_data

	def self.create_user(auth)
		logger.debug(auth)
		@@auth_data = auth

		logger.debug("success")
	end

	def self.getData() 
		return @@auth_data
	end
end

app/controllers/my_teams_controller.rb
class MyTeamsController < ApplicationController
	helper_method :current_diary, :getsubTitle, :getData, :getCreateTime
	include ApplicationHelper

	def index
		@user = user();

	    if @user.team_id == nil
	    	redirect_to ({:controller => "teams", :action =>"index"}), :notice => "チームに入ってください"
		else 
			@diary = Diary.find(:all, :conditions => {:team_id => @user.team_id})
 		    @diary = @diary.reverse
			@team = Team.find_by :id => @user.team_id
			@teams_photo = TeamAlbum.find(:all, :conditions => {:team_id => @user.team_id})
			@comment = Comment.new
		end
	end

	def like
    	like_do(params[:id])

    	render
	end


	def confirm
	    logger.debug 'success'
	    logger.debug current_diary(params[:id])
	    @title = params[:id]
	    @comment_lists = Comment.find(:all, :conditions => { :diary_id => @current_diary.id})
	    
	    @comment = Comment.new
	    @comment.user_id = session[:user_id]
	    @comment.diary_id = @current_diary.id

	    render
 	end


 	def like(diary_id = 1)
      logger.debug diary_id
      user = user();
      @diary = Diary.find_by :id => diary_id
      logger.debug 'called like helper method by views'
      num = @diary.reputation_for(:likes).to_i

      begin 
        @diary.add_evaluation(:likes, num + 1, user)
      rescue
        @diary.add_or_update_evaluation(:likes, num-1, user)
      end
    end
    private
 	    def current_diary(diary_id) 
    	  @diary = Diary.find_by :id => diary_id
      	  @current_diary = @diary
	      return diary_id
	    end   

	    def getsubTitle() 
	      return @current_diary.subtitle
	    end

	    def getData()
	      @records = Record.find(:all, :conditions => {:title => @current_diary.subtitle})

	      data = []
	      @records.each do |r|
	        timeAry = r.time.split(".")
	        logger.debug timeAry[1]
	        logger.debug timeAry[1].to_f / 60
	        result = timeAry[0].to_f + timeAry[1].to_f/60
	        data.push result
	      end


	      return data
	    end

	    def like_do(diary_id = 1)
	      logger.debug diary_id
	      user = user();
	      user = User.find_by :id => session[:user_id]
	      diary = Diary.find_by :id => diary_id
	      logger.debug 'called like helper method by views'

	      begin 
	        diary.add_evaluation(:likes, 1, user)
	        redirect_to index_path
	      rescue
	        diary.add_or_update_evaluation(:likes, -1, user)
	        redirect_to index_path
	      end
	    end


	    def getCreateTime() 
	      @records = Record.find(:all, :conditions => {:title => @current_diary.subtitle})
	      data = []
	      
	      @record.each do |r|
	        data.push r.created_at
	      end

	      return data
	    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/lp_helper.rb
module LpHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper

	def like(diary_id = 1)
		logger.debug diary_id
		user = User.find_by :id => session[:user_id]
		diary = Diary.find_by :id => diary_id
		logger.debug 'called like helper method by views'

		# begin 
		#   diary.add_evaluation(:likes, 1, user)
		#   redirect_to index_path
		# rescue
		#   diary.add_or_update_evaluation(:likes, -1, user)
		#   redirect_to index_path
		# end
  	end

	
end

app/helpers/my_team_helper.rb
module MyTeamHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tech_logs_helper.rb
module TechLogsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/my_teams/confirm.js.erb
console.log("reder to confirm.js.erb");
console.log("<%= @title %>");
var button = document.getElementById("dialog");
var user_id = document.getElementById("comment_user");
var diary_id = document.getElementById("comment_diary");
var list = document.getElementById("comment_lists");
var graph_data = <%= getData() %>;

user_id.value = "<%= @comment.user_id %>";
diary_id.value = "<%= @comment.diary_id %>";
// user_id.value = @comment.user_id;
$('#chart').highcharts({
  title: {
      text: "<%= getsubTitle() %>",
  },
  tooltip: {
      valueSuffix: '[分]'
  },
  legend: {
      layout: 'vertical',
      align: 'right',
      verticalAlign: 'middle',
      borderWidth: 0
  },
  series: [{
      data: graph_data
  }]
});
button.click();


removeChildren(list);
var modal = document.getElementById("modal");
var height = 550 + 60 * <%= @comment_lists.size %>;
console.log(height);
modal.style.height =  height + "px";

<% @comment_lists.each do |com| %>

  console.log("<%= com.comment %>");
  var li = document.createElement("div");
  li.className = "well";
  <% user = user() %>
  li.textContent ="<%= user.name %>" + ": " + "<%= com.comment %>";

  list.appendChild(li); 

<% end %>

function removeChildren(x)
{
  if (x.hasChildNodes()) {
    while (x.childNodes.length > 0) {
      x.removeChild(x.firstChild)
    }
  }
}

app/views/my_teams/index.html.slim
= stylesheet_link_tag "bootstrap", :media => "all"
= stylesheet_link_tag "style", :media => "all"
= stylesheet_link_tag "perfect-scrollbar", :media => "all"
= stylesheet_link_tag "font-awesome", :media => "all"
= stylesheet_link_tag "freelancer", :media => "all"
= stylesheet_link_tag "fallback", :media => "all"
link[href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,600,700,800,300" rel="stylesheet" type="text/css"]
header
  #banner.banner.row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12.noPadd.slides-container[style="height:100%"]
      .slide
        .bannerText.container
          h1
            = @team.destination
          = link_to 'New Diary', new_diary_path, :class => "mbnt"
        = image_tag @team.image.url, :width => '100%', :height => '100%'
.menu
  .navbar-wrapper
    .container
      .navwrapper
        .navbar.navbar-inverse.navbar-static-top
          .container
            .navbar-header
              button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
                span.icon-bar
                span.icon-bar
                span.icon-bar
              a.navbar-brand[href="#"]
                | Menu
            .navbar-collapse.collapse
              ul.nav.navbar-nav.nav-justified
                li.first.menuItem.homeLink.active
                  = link_to 'HOME', index_path
                li.menuItem
                  = link_to 'My team', my_teams_path
                li.menuItem
                  = link_to 'Skills', tech_logs_path
                li.menuItem
                  = link_to 'Edit team', edit_team_path(@team)
                li.menuItem
                  = link_to 'Member',
                     members_index_path
                / li.menuItem
                /   = link_to 'Schedule', 

section#reffernces.reffernces
  .container
    .heading
      h2
        | Team's diary
    - @diary.each do |d|
      .row.workDetails
        .col-xs-12.col-sm-3.col-md-2.col-lg-2
          .workYear
            span.prevY
              = d.date
            button.btn.btn-default.detail[data-toggle = "modal" style="display:none;" data-target = "#diary_detail" id = "dialog" ] detail
            = form_tag(url_for(:controller => 'my_teams', :action => 'confirm'), :remote => true) do
              = hidden_field_tag "id", d.id
              = submit_tag "detail",:class => "btn btn-danger",:'data-target' => "#diary_detail"


        .col-xs-12.col-sm-9.col-md-10.col-lg-10.rightArea
          |  <div class="arrowpart" style="background-image:url(
          = asset_path "arrow-left.png"
          | )">
        .exCon
          - if d.user_id != nil
            - user_name = User.find_by(:id => d.user_id);
          - else 
            - user_name = GeneralUser.find_by(:id => d.likes);
          h4
            = d.menu
            | ~ #{user_name.name} ~
          h5
            = d.subtitle
          - @com = Comment.find(:all, :conditions => {:diary_id => d.id})
          p
            - d.other = h(d.other).gsub(/(\r\n?)|(\n)/, "<br />").html_safe
            = d.other
          p.comment
            | コメント : #{@com.size} 
          = form_tag(url_for(:controller => 'my_teams', :action => 'like'), :remote => true) do
            = hidden_field_tag "id", d.id
            = submit_tag "いいね : #{d.reputation_for(:likes).to_i}", :class => "like", :id => "like"

section#reffernces.reffernces
  .container
    .heading
      h2
        | Team's Gallery
    center
    center.pad
      = link_to 'upload photo', new_team_album_path, :class => "mbnt"

    ul.portfolioContainer.row.gallery
      - @teams_photo.each do |photo|
        li.branding.illustration.col-xs-6.col-sm-4.col-md-3.col-lg-3
          div.lightCon 
            span.hoverBox
            = image_tag photo.image.url, :width => "100%"




div.modal.fade[id="diary_detail" role="dialog"]
  .modal-dialog
    .modal-content
      .modal-header
        button.close[id = "close" data-dismiss="modal"]
          span[aria-hidden="true"]&times;

        h4.modal-title[id="label"] 日誌詳細
      .modal-body[id="modal"]
        center
          div[id="chart" width="400px" height="300px"]
        div[id="comment_lists"]
        / = form_for(@comment) do |f| 
        /   .field

        /     = f.text_field :comment 
        /   .field
        /     = f.hidden_field :user_id 
        /   .field
        /     = f.hidden_field :diary_id 
        /   .actions
        /     = f.submit

      .modal-footer
        = form_for(@comment, :url => {:controller => 'comments', :action => 'save_comment'}, :remote => true) do |f| 
          .input-group.style
            = f.text_field :comment, :class => "form-control col-sm-9"
            input[id="comment_user" name="user_id" type="hidden"]
            input[id="comment_diary" name="diary_id" type="hidden"]
            / = f.text_field :user_id
            / = f.text_field :diary_id
            .actions
              =f.submit 'submit', :class => "btn btn-default col-sm-2"


  javascript:
    $('#banner').superslides({
    }); 

  javascript:
    $(document).ready(function ($) {
      $('#description').perfectScrollbar({
        wheelSpeed: 20,
        wheelPropagation: false 
      }); 
    });

app/views/my_teams/like.js.erb
var like = document.getElementById("like");

like.value = "いいね : <%= @diary.reputation_for(:likes).to_i %>";