config/routes.rb
Run::Application.routes.draw do

  devise_for :general_users , :controllers => { :registrations => "general_users/registrations" , :sessions => "general_users/sessions" }
  resources :comments

  resources :records

  resources :team_albums

  resources :diary_images

  resources :teams

  resources :diaries

  resources :users
  resources :my_teams

  get "/auth/:provider/callback" => "sessions#callback"
  get '/index' => 'my_pages#index'
  get "teams/pass_check"
  post "/login" => "sessions#check"
  get '/sign_up' => "devise/registrations#new"
  post "teams/pass_check"
  post "teams/show"
  post 'my_pages/like'
  post 'my_pages/confirm'
  post 'my_teams/confirm'
  post 'my_teams/like'
  post 'diaries/data_save'
  post 'comments/save_comment' 
  get '/my_teams' => 'my_teams#index'
  get 'my_pages/like'
  get 'lps/index' => 'lps#index'
  get 'members/index'

  root :to => "my_pages#index"

  resources :tech_logs
  resources :members

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/diary.rb
class Diary < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :users
	has_reputation :likes, source: :user, aggregated_by: :sum

	validates :menu, presence: true
	validates :date, presence: true
	validates :subtitle, presence: true
	validates :other, presence: true


end

app/models/diary_image.rb
class DiaryImage < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/diary_images.rb
class DiaryImages < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/general_user.rb
class GeneralUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
  mount_uploader :image, ImageUploader

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_secure_password 
	validates :name, presence: true
	validates :destination , presence: true
	validates :image, presence: true
end

app/models/team_album.rb
class TeamAlbum < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :image, presence: true
	validates :title, presence: true
end

app/models/tech_log.rb
class TechLog < ActiveRecord::Base
	mount_uploader :video, VideoUploader

	validates :title, presence: true
	validates :video, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :name, presence: true
	validates :destination, presence: true

	@@auth_data

	def self.create_user(auth)
		logger.debug(auth)
		@@auth_data = auth

		logger.debug("success")
	end

	def self.getData() 
		return @@auth_data
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = params[:user_id]
    @comment.diary_id = params[:diary_id]

    if @comment.save
      format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
      format.json { render action: 'show', status: :created, location: @comment }
    else
      format.html { render action: 'new' }
      format.json { render json: @comment.errors, status: :unprocessable_entity }
    end
  end

  def save_comment
    @comment = Comment.new
    @comment.user_id = params[:user_id]
    @comment.diary_id = params[:diary_id]
    @comment.comment = params[:comment][:comment]

    if @comment.save
      render
    else
            
    end

  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :user_id, :diary_id)
    end
end

app/controllers/lps_controller.rb
class LpsController < ApplicationController

	before_action :authenticate_general_user!

	def index
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/lp_helper.rb
module LpHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper

	def like(diary_id = 1)
		logger.debug diary_id
		user = User.find_by :id => session[:user_id]
		diary = Diary.find_by :id => diary_id
		logger.debug 'called like helper method by views'

		# begin 
		#   diary.add_evaluation(:likes, 1, user)
		#   redirect_to index_path
		# rescue
		#   diary.add_or_update_evaluation(:likes, -1, user)
		#   redirect_to index_path
		# end
  	end

	
end

app/helpers/my_team_helper.rb
module MyTeamHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tech_logs_helper.rb
module TechLogsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :diary_id %><br>
    <%= f.number_field :diary_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>User</th>
      <th>Diary</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.diary_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/save_comment.js.erb
var close = document.getElementById("close");

close.click();

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Diary:</strong>
  <%= @comment.diary_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>