config/routes.rb
Run::Application.routes.draw do

  devise_for :general_users , :controllers => { :registrations => "general_users/registrations" , :sessions => "general_users/sessions" }
  resources :comments

  resources :records

  resources :team_albums

  resources :diary_images

  resources :teams

  resources :diaries

  resources :users
  resources :my_teams

  get "/auth/:provider/callback" => "sessions#callback"
  get '/index' => 'my_pages#index'
  get "teams/pass_check"
  post "/login" => "sessions#check"
  get '/sign_up' => "devise/registrations#new"
  post "teams/pass_check"
  post "teams/show"
  post 'my_pages/like'
  post 'my_pages/confirm'
  post 'my_teams/confirm'
  post 'my_teams/like'
  post 'diaries/data_save'
  post 'comments/save_comment' 
  get '/my_teams' => 'my_teams#index'
  get 'my_pages/like'
  get 'lps/index' => 'lps#index'
  get 'members/index'

  root :to => "my_pages#index"

  resources :tech_logs
  resources :members

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/diary.rb
class Diary < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :users
	has_reputation :likes, source: :user, aggregated_by: :sum

	validates :menu, presence: true
	validates :date, presence: true
	validates :subtitle, presence: true
	validates :other, presence: true


end

app/models/diary_image.rb
class DiaryImage < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/diary_images.rb
class DiaryImages < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/general_user.rb
class GeneralUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
  mount_uploader :image, ImageUploader

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_secure_password 
	validates :name, presence: true
	validates :destination , presence: true
	validates :image, presence: true
end

app/models/team_album.rb
class TeamAlbum < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :image, presence: true
	validates :title, presence: true
end

app/models/tech_log.rb
class TechLog < ActiveRecord::Base
	mount_uploader :video, VideoUploader

	validates :title, presence: true
	validates :video, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :name, presence: true
	validates :destination, presence: true

	@@auth_data

	def self.create_user(auth)
		logger.debug(auth)
		@@auth_data = auth

		logger.debug("success")
	end

	def self.getData() 
		return @@auth_data
	end
end

app/controllers/lps_controller.rb
class LpsController < ApplicationController

	before_action :authenticate_general_user!

	def index
	end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @record }
      else
        format.html { render action: 'new' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:title, :time, :user_id, :diary_id, :lap, :rlp)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/lp_helper.rb
module LpHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper

	def like(diary_id = 1)
		logger.debug diary_id
		user = User.find_by :id => session[:user_id]
		diary = Diary.find_by :id => diary_id
		logger.debug 'called like helper method by views'

		# begin 
		#   diary.add_evaluation(:likes, 1, user)
		#   redirect_to index_path
		# rescue
		#   diary.add_or_update_evaluation(:likes, -1, user)
		#   redirect_to index_path
		# end
  	end

	
end

app/helpers/my_team_helper.rb
module MyTeamHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tech_logs_helper.rb
module TechLogsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/records/_form.html.haml
= form_for @record do |f|
  - if @record.errors.any?
    #error_explanation
      %h2= "#{pluralize(@record.errors.count, "error")} prohibited this record from being saved:"
      %ul
        - @record.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :time
    = f.text_field :time
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :diary_id
    = f.text_field :diary_id
  .field
    = f.label :lap
    = f.text_field :lap
  .field
    = f.label :rlp
    = f.text_field :rlp
  .actions
    = f.submit 'Save'

app/views/records/edit.html.haml
%h1 Editing record

= render 'form'

= link_to 'Show', @record
\|
= link_to 'Back', records_path

app/views/records/index.html.haml
%h1 Listing records

%table
  %tr
    %th Title
    %th Time
    %th User
    %th Diary
    %th Lap
    %th Rlp
    %th
    %th
    %th

  - @records.each do |record|
    %tr
      %td= record.title
      %td= record.time
      %td= record.user_id
      %td= record.diary_id
      %td= record.lap
      %td= record.rlp
      %td= link_to 'Show', record
      %td= link_to 'Edit', edit_record_path(record)
      %td= link_to 'Destroy', record, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Record', new_record_path

app/views/records/new.html.haml
%h1 New record

= render 'form'

= link_to 'Back', records_path

app/views/records/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @record.title
%p
  %b Time:
  = @record.time
%p
  %b User:
  = @record.user_id
%p
  %b Diary:
  = @record.diary_id
%p
  %b Lap:
  = @record.lap
%p
  %b Rlp:
  = @record.rlp

= link_to 'Edit', edit_record_path(@record)
\|
= link_to 'Back', records_path