config/routes.rb
Run::Application.routes.draw do

  devise_for :general_users , :controllers => { :registrations => "general_users/registrations" , :sessions => "general_users/sessions" }
  resources :comments

  resources :records

  resources :team_albums

  resources :diary_images

  resources :teams

  resources :diaries

  resources :users
  resources :my_teams

  get "/auth/:provider/callback" => "sessions#callback"
  get '/index' => 'my_pages#index'
  get "teams/pass_check"
  post "/login" => "sessions#check"
  get '/sign_up' => "devise/registrations#new"
  post "teams/pass_check"
  post "teams/show"
  post 'my_pages/like'
  post 'my_pages/confirm'
  post 'my_teams/confirm'
  post 'my_teams/like'
  post 'diaries/data_save'
  post 'comments/save_comment' 
  get '/my_teams' => 'my_teams#index'
  get 'my_pages/like'
  get 'lps/index' => 'lps#index'
  get 'members/index'

  root :to => "my_pages#index"

  resources :tech_logs
  resources :members

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/diary.rb
class Diary < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :users
	has_reputation :likes, source: :user, aggregated_by: :sum

	validates :menu, presence: true
	validates :date, presence: true
	validates :subtitle, presence: true
	validates :other, presence: true


end

app/models/diary_image.rb
class DiaryImage < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/diary_images.rb
class DiaryImages < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/general_user.rb
class GeneralUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
  mount_uploader :image, ImageUploader

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_secure_password 
	validates :name, presence: true
	validates :destination , presence: true
	validates :image, presence: true
end

app/models/team_album.rb
class TeamAlbum < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :image, presence: true
	validates :title, presence: true
end

app/models/tech_log.rb
class TechLog < ActiveRecord::Base
	mount_uploader :video, VideoUploader

	validates :title, presence: true
	validates :video, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :name, presence: true
	validates :destination, presence: true

	@@auth_data

	def self.create_user(auth)
		logger.debug(auth)
		@@auth_data = auth

		logger.debug("success")
	end

	def self.getData() 
		return @@auth_data
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	include ApplicationHelper

	def index
		@user = user()
		@team = Team.find_by :id => @user.team_id
		@member = User.find(:all, :conditions =>{ :team_id => @team.id})
	end

	def show
		@user = user()
		@diary = Diary.find(:all, :conditions => { :user_id => params[:id]});

		logger.debug @diary
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/lp_helper.rb
module LpHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper

	def like(diary_id = 1)
		logger.debug diary_id
		user = User.find_by :id => session[:user_id]
		diary = Diary.find_by :id => diary_id
		logger.debug 'called like helper method by views'

		# begin 
		#   diary.add_evaluation(:likes, 1, user)
		#   redirect_to index_path
		# rescue
		#   diary.add_or_update_evaluation(:likes, -1, user)
		#   redirect_to index_path
		# end
  	end

	
end

app/helpers/my_team_helper.rb
module MyTeamHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tech_logs_helper.rb
module TechLogsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/members/index.html.slim
link[href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,600,700,800,300" rel="stylesheet" type="text/css"]
header
  #banner.banner.row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12.noPadd.slides-container[style="height:100%"]
      .slide
        .bannerText.container
          h1
            = @team.destination
          = link_to 'New Diary', new_diary_path, :class => "mbnt"
        = image_tag @team.image.url, :width => '100%', :height => '100%'
.menu
  .navbar-wrapper
    .container
      .navwrapper
        .navbar.navbar-inverse.navbar-static-top
          .container
            .navbar-header
              button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
                span.icon-bar
                span.icon-bar
                span.icon-bar
              a.navbar-brand[href="#"]
                | Menu
            .navbar-collapse.collapse
              ul.nav.navbar-nav.nav-justified
                li.first.menuItem.homeLink.active
                  = link_to 'HOME', index_path
                li.menuItem
                  = link_to 'My team', my_teams_path
                li.menuItem
                  = link_to 'Skills', tech_logs_path
                li.menuItem
                  = link_to 'Edit team', edit_team_path(@team)
                li.menuItem
                  = link_to 'Member', members_index_path


section#reffernces.reffernces
  .container
    center
      h2
        | members
    table.table.table-hover
      thead
        tr
          th
            | サムネイル

          th
            | 名前
          th
            | 目標
      tbody
        - @member.each do |m|
          tr
            td
              = image_tag m.image.url , :width => "100"
            td
              = link_to m.name, member_path(m), :id => "link"
            td[id="destination"]
              = m.destination

app/views/members/show.html.slim
link[href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,600,700,800,300" rel="stylesheet" type="text/css"]
header
  #banner.banner.row
    .col-xs-12.col-sm-12.col-md-12.col-lg-12.noPadd.slides-container[style="height:100%"]
      .slide
        .bannerText.container
          h1
            = @user.destination
        = image_tag @user.image.url, :width => '100%', :height => '100%'
.menu
  .navbar-wrapper
    .container
      .navwrapper
        .navbar.navbar-inverse.navbar-static-top
          .container
            .navbar-header
              button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
                span.icon-bar
                span.icon-bar
                span.icon-bar
              a.navbar-brand[href="#"]
                | Menu
            .navbar-collapse.collapse
              ul.nav.navbar-nav.nav-justified
                li.first.menuItem.homeLink.active
                  = link_to 'HOME', index_path


section#reffernces.reffernces
  .container
    center
      h2
        | #{@user.name}

    - @diary.each do |d|
      .row.workDetails
        .col-xs-12.col-sm-3.col-md-2.col-lg-2
          .workYear
            span.prevY
              = d.date
            button.btn.btn-default.detail[data-toggle = "modal" style="display:none;" data-target = "#diary_detail" id = "dialog" ] detail
            = form_tag(url_for(:controller => 'my_teams', :action => 'confirm'), :remote => true) do
              = hidden_field_tag "id", d.id
              = submit_tag "detail",:class => "btn btn-danger",:'data-target' => "#diary_detail"


        .col-xs-12.col-sm-9.col-md-10.col-lg-10.rightArea
          |  <div class="arrowpart" style="background-image:url(
          = asset_path "arrow-left.png"
          | )">
        .exCon
          h4
            = d.menu
          h5
            = d.subtitle
          - @com = Comment.find(:all, :conditions => {:diary_id => d.id})
          p
            - d.other = h(d.other).gsub(/(\r\n?)|(\n)/, "<br />").html_safe
            = d.other
          p.comment
            | コメント : #{@com.size} 
          = form_tag(url_for(:controller => 'my_teams', :action => 'like'), :remote => true) do
            = hidden_field_tag "id", d.id
            = submit_tag "いいね : #{d.reputation_for(:likes).to_i}", :class => "like", :id => "like"